import type { SiteContent, TemplateId, Vibe } from "./types";

// A "theme" is a complete visual identity — palette, type pairing, hero layout, card
// treatment, section divider, and services layout. Selection order: explicit editor
// pick (content.themeId) → AI vibe narrows the category pool → deterministic seed.
// Every color is a token so full-dark themes work with the same renderer.

export type HeroStyle = "left" | "center" | "split";
export type CardStyle = "border" | "shadow" | "filled";
export type ServiceStyle = "grid" | "rows";
export type Divider = "none" | "wave" | "slant";

export type Theme = {
  id: string;
  label: string;
  categories: TemplateId[];
  vibes: Vibe[];
  // palette
  accent: string;
  accent2: string;
  ink: string;
  muted: string;
  bg: string;
  surface: string;
  card: string;
  border: string;
  inputBg: string;
  // hero
  heroBg: string;
  heroText: string;
  heroMuted: string;
  onAccent: string;
  // typography
  headingFont: string;
  bodyFont: string;
  googleFonts: string;
  radius: number;
  borderW: number;
  heroStyle: HeroStyle;
  cardStyle: CardStyle;
  serviceStyle: ServiceStyle;
  divider: Divider;
  /** Full dark page (not just a dark hero). */
  dark?: boolean;
};

const gf = (families: string) =>
  `https://fonts.googleapis.com/css2?${families}&display=swap`;

export const THEMES: Theme[] = [
  {
    id: "noir",
    label: "Noir — tumma & tyylikäs",
    categories: ["salon", "hospitality"],
    vibes: ["luxury", "elegant"],
    accent: "#b76e79",
    accent2: "#d8a7b1",
    ink: "#211b1e",
    muted: "#6b5f63",
    bg: "#faf7f5",
    surface: "#f3ebe9",
    card: "#ffffff",
    border: "#e7dcd9",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #17131a, #2a1f28)",
    heroText: "#fdf7f5",
    heroMuted: "#d9c7cd",
    onAccent: "#ffffff",
    headingFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Playfair+Display:wght@600;700&family=Inter:wght@400;500;600"),
    radius: 4,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "none",
  },
  {
    id: "blush",
    label: "Blush — pehmeä & naisellinen",
    categories: ["salon"],
    vibes: ["warm", "elegant"],
    accent: "#d6336c",
    accent2: "#f06595",
    ink: "#2b1a22",
    muted: "#7a5c67",
    bg: "#ffffff",
    surface: "#fff5f8",
    card: "#ffffff",
    border: "#f6dfe8",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #fff0f5, #ffe3ee)",
    heroText: "#2b1a22",
    heroMuted: "#7a5c67",
    onAccent: "#ffffff",
    headingFont: "'Cormorant Garamond', Georgia, serif",
    bodyFont: "'Montserrat', system-ui, sans-serif",
    googleFonts: gf("family=Cormorant+Garamond:wght@600;700&family=Montserrat:wght@400;500;600"),
    radius: 20,
    borderW: 1,
    heroStyle: "center",
    cardStyle: "filled",
    serviceStyle: "grid",
    divider: "wave",
  },
  {
    id: "sage",
    label: "Sage — rauhallinen vihreä",
    categories: ["salon", "trades"],
    vibes: ["minimal", "fresh"],
    accent: "#5f7a5f",
    accent2: "#86a586",
    ink: "#1f251f",
    muted: "#5c665c",
    bg: "#f7f9f6",
    surface: "#eef3ec",
    card: "#ffffff",
    border: "#dde6da",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #eef3ec, #e2ebdf)",
    heroText: "#1f251f",
    heroMuted: "#5c665c",
    onAccent: "#ffffff",
    headingFont: "'Fraunces', Georgia, serif",
    bodyFont: "'Nunito Sans', system-ui, sans-serif",
    googleFonts: gf("family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Nunito+Sans:wght@400;600;700"),
    radius: 14,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "border",
    serviceStyle: "rows",
    divider: "none",
  },
  {
    id: "steel",
    label: "Steel — sininen & luotettava",
    categories: ["trades"],
    vibes: ["bold", "minimal"],
    accent: "#2563eb",
    accent2: "#3b82f6",
    ink: "#111827",
    muted: "#4b5563",
    bg: "#ffffff",
    surface: "#f1f5f9",
    card: "#ffffff",
    border: "#e2e8f0",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #eff5ff, #e3edfd)",
    heroText: "#0b1220",
    heroMuted: "#475569",
    onAccent: "#ffffff",
    headingFont: "'Space Grotesk', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600"),
    radius: 8,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "slant",
  },
  {
    id: "industrial",
    label: "Industrial — tumma & voimakas",
    categories: ["trades", "hospitality"],
    vibes: ["bold"],
    accent: "#ea580c",
    accent2: "#fb923c",
    ink: "#1c1917",
    muted: "#57534e",
    bg: "#fafaf9",
    surface: "#f5f5f4",
    card: "#ffffff",
    border: "#e7e5e4",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #1c1917, #292420)",
    heroText: "#fafaf9",
    heroMuted: "#d6cfc8",
    onAccent: "#ffffff",
    headingFont: "'Archivo', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Archivo:wght@600;800&family=Inter:wght@400;500;600"),
    radius: 6,
    borderW: 1,
    heroStyle: "center",
    cardStyle: "filled",
    serviceStyle: "rows",
    divider: "slant",
  },
  {
    id: "forest",
    label: "Forest — raikas metsänvihreä",
    categories: ["trades"],
    vibes: ["fresh", "warm"],
    accent: "#15803d",
    accent2: "#22c55e",
    ink: "#14231a",
    muted: "#4b5f52",
    bg: "#ffffff",
    surface: "#f0fdf4",
    card: "#ffffff",
    border: "#d7efe0",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #ecfdf3, #dcfce7)",
    heroText: "#0f2318",
    heroMuted: "#43604e",
    onAccent: "#ffffff",
    headingFont: "'Manrope', system-ui, sans-serif",
    bodyFont: "'Manrope', system-ui, sans-serif",
    googleFonts: gf("family=Manrope:wght@400;600;800"),
    radius: 12,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "border",
    serviceStyle: "grid",
    divider: "wave",
  },
  {
    id: "slate",
    label: "Slate — selkeä teal",
    categories: ["trades", "salon"],
    vibes: ["minimal"],
    accent: "#0f766e",
    accent2: "#14b8a6",
    ink: "#0f1c1b",
    muted: "#4b5b5a",
    bg: "#ffffff",
    surface: "#f0fdfa",
    card: "#ffffff",
    border: "#dceeec",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #effcfa, #ddf6f3)",
    heroText: "#0b1a19",
    heroMuted: "#456260",
    onAccent: "#ffffff",
    headingFont: "'Inter', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Inter:wght@400;500;600;800"),
    radius: 12,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "none",
  },
  {
    id: "terracotta",
    label: "Terracotta — lämmin savi",
    categories: ["hospitality", "trades"],
    vibes: ["warm"],
    accent: "#c2410c",
    accent2: "#ea580c",
    ink: "#26160f",
    muted: "#6f574c",
    bg: "#fffaf5",
    surface: "#fdf1e7",
    card: "#ffffff",
    border: "#f3e1d2",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #fdefe2, #f9ddc7)",
    heroText: "#26160f",
    heroMuted: "#6f574c",
    onAccent: "#ffffff",
    headingFont: "'Fraunces', Georgia, serif",
    bodyFont: "'Karla', system-ui, sans-serif",
    googleFonts: gf("family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Karla:wght@400;600;700"),
    radius: 16,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "filled",
    serviceStyle: "rows",
    divider: "wave",
  },
  {
    id: "bordeaux",
    label: "Bordeaux — viininpunainen klassikko",
    categories: ["hospitality"],
    vibes: ["luxury", "elegant"],
    accent: "#9f1239",
    accent2: "#be123c",
    ink: "#241017",
    muted: "#6f5259",
    bg: "#fdf9f9",
    surface: "#f6eaec",
    card: "#ffffff",
    border: "#ecd6da",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #1a1113, #2c1a1f)",
    heroText: "#fdf4f5",
    heroMuted: "#dcc3c8",
    onAccent: "#ffffff",
    headingFont: "'DM Serif Display', Georgia, serif",
    bodyFont: "'DM Sans', system-ui, sans-serif",
    googleFonts: gf("family=DM+Serif+Display&family=DM+Sans:wght@400;500;700"),
    radius: 4,
    borderW: 1,
    heroStyle: "center",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "none",
  },
  {
    id: "honey",
    label: "Honey — aurinkoinen hunaja",
    categories: ["hospitality", "salon"],
    vibes: ["warm", "fresh"],
    accent: "#b45309",
    accent2: "#d97706",
    ink: "#271c0e",
    muted: "#6d5c44",
    bg: "#fffbeb",
    surface: "#fef3c7",
    card: "#ffffff",
    border: "#f3e6bf",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #fff7e0, #fdecc0)",
    heroText: "#271c0e",
    heroMuted: "#6d5c44",
    onAccent: "#ffffff",
    headingFont: "'Fraunces', Georgia, serif",
    bodyFont: "'DM Sans', system-ui, sans-serif",
    googleFonts: gf("family=Fraunces:opsz,wght@9..144,500;9..144,600&family=DM+Sans:wght@400;500;700"),
    radius: 18,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "border",
    serviceStyle: "grid",
    divider: "wave",
  },
  // ---------------- new themes ----------------
  {
    id: "midnight",
    label: "Midnight — kokonaan tumma",
    categories: ["trades", "salon"],
    vibes: ["bold", "luxury"],
    accent: "#818cf8",
    accent2: "#22d3ee",
    ink: "#eef0ff",
    muted: "#9aa1b5",
    bg: "#0b0d14",
    surface: "#12151f",
    card: "#161a27",
    border: "#252b3d",
    inputBg: "#0e1119",
    heroBg: "radial-gradient(1100px 500px at 70% -10%, rgba(129,140,248,.28), transparent), linear-gradient(160deg, #0b0d14, #131629)",
    heroText: "#f4f5ff",
    heroMuted: "#a6adc4",
    onAccent: "#0b0d14",
    headingFont: "'Sora', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Sora:wght@500;700&family=Inter:wght@400;500;600"),
    radius: 14,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "border",
    serviceStyle: "grid",
    divider: "slant",
    dark: true,
  },
  {
    id: "aurora",
    label: "Aurora — värikäs gradientti",
    categories: ["salon", "hospitality"],
    vibes: ["fresh", "bold"],
    accent: "#7c3aed",
    accent2: "#ec4899",
    ink: "#1e1b2e",
    muted: "#5f5a75",
    bg: "#ffffff",
    surface: "#faf5ff",
    card: "#ffffff",
    border: "#ecdff9",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(120deg, #ede9fe 0%, #fce7f3 55%, #e0f2fe 100%)",
    heroText: "#1e1b2e",
    heroMuted: "#5f5a75",
    onAccent: "#ffffff",
    headingFont: "'Outfit', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Outfit:wght@500;700&family=Inter:wght@400;500;600"),
    radius: 22,
    borderW: 1,
    heroStyle: "center",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "wave",
  },
  {
    id: "editorial",
    label: "Editorial — lehtimäinen",
    categories: ["hospitality", "salon"],
    vibes: ["elegant", "minimal"],
    accent: "#1c1917",
    accent2: "#78716c",
    ink: "#1c1917",
    muted: "#57534e",
    bg: "#faf9f7",
    surface: "#f3f1ec",
    card: "#faf9f7",
    border: "#d6d1c7",
    inputBg: "#ffffff",
    heroBg: "#faf9f7",
    heroText: "#1c1917",
    heroMuted: "#57534e",
    onAccent: "#faf9f7",
    headingFont: "'Lora', Georgia, serif",
    bodyFont: "'Mulish', system-ui, sans-serif",
    googleFonts: gf("family=Lora:wght@500;600;700&family=Mulish:wght@400;600;700"),
    radius: 0,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "border",
    serviceStyle: "rows",
    divider: "none",
  },
  {
    id: "ocean",
    label: "Ocean — syvänsininen",
    categories: ["trades", "hospitality"],
    vibes: ["fresh", "minimal"],
    accent: "#0369a1",
    accent2: "#06b6d4",
    ink: "#0c1a24",
    muted: "#47606e",
    bg: "#ffffff",
    surface: "#f0f9ff",
    card: "#ffffff",
    border: "#d9edf7",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #06283d, #0b4f6c)",
    heroText: "#f0f9ff",
    heroMuted: "#b6d9ea",
    onAccent: "#ffffff",
    headingFont: "'Figtree', system-ui, sans-serif",
    bodyFont: "'Figtree', system-ui, sans-serif",
    googleFonts: gf("family=Figtree:wght@400;600;800"),
    radius: 12,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "shadow",
    serviceStyle: "grid",
    divider: "wave",
  },
  {
    id: "brutal",
    label: "Brutal — rohkea & suorakulmainen",
    categories: ["trades"],
    vibes: ["bold"],
    accent: "#111111",
    accent2: "#facc15",
    ink: "#111111",
    muted: "#4b4b4b",
    bg: "#f7f6f3",
    surface: "#efede8",
    card: "#ffffff",
    border: "#111111",
    inputBg: "#ffffff",
    heroBg: "#f7f6f3",
    heroText: "#111111",
    heroMuted: "#4b4b4b",
    onAccent: "#ffffff",
    headingFont: "'Archivo', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Archivo:wght@700;900&family=Inter:wght@400;500;600"),
    radius: 0,
    borderW: 2,
    heroStyle: "center",
    cardStyle: "border",
    serviceStyle: "rows",
    divider: "slant",
  },
  {
    id: "lavender",
    label: "Lavender — hento violetti",
    categories: ["salon"],
    vibes: ["elegant", "fresh"],
    accent: "#7e5bef",
    accent2: "#a78bfa",
    ink: "#241f36",
    muted: "#645d7d",
    bg: "#fdfcff",
    surface: "#f4f0fe",
    card: "#ffffff",
    border: "#e6ddfb",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #f2ecfe, #e8e2fc)",
    heroText: "#241f36",
    heroMuted: "#645d7d",
    onAccent: "#ffffff",
    headingFont: "'Quicksand', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Quicksand:wght@500;700&family=Inter:wght@400;500;600"),
    radius: 24,
    borderW: 1,
    heroStyle: "center",
    cardStyle: "filled",
    serviceStyle: "grid",
    divider: "wave",
  },
  {
    id: "copper",
    label: "Copper — tumma pronssi",
    categories: ["hospitality"],
    vibes: ["luxury", "warm"],
    accent: "#d69e6b",
    accent2: "#e7bd93",
    ink: "#f3e9df",
    muted: "#b3a292",
    bg: "#181210",
    surface: "#211915",
    card: "#261d18",
    border: "#3a2d24",
    inputBg: "#1d1512",
    heroBg: "radial-gradient(900px 420px at 30% -10%, rgba(214,158,107,.22), transparent), #181210",
    heroText: "#f6ede2",
    heroMuted: "#c8b6a4",
    onAccent: "#181210",
    headingFont: "'Marcellus', Georgia, serif",
    bodyFont: "'Jost', system-ui, sans-serif",
    googleFonts: gf("family=Marcellus&family=Jost:wght@400;500;600"),
    radius: 6,
    borderW: 1,
    heroStyle: "split",
    cardStyle: "border",
    serviceStyle: "rows",
    divider: "none",
    dark: true,
  },
  {
    id: "nordic",
    label: "Nordic — ilmava & pohjoismainen",
    categories: ["trades", "salon", "hospitality"],
    vibes: ["minimal", "fresh"],
    accent: "#334155",
    accent2: "#64748b",
    ink: "#0f172a",
    muted: "#526077",
    bg: "#ffffff",
    surface: "#f6f8fb",
    card: "#ffffff",
    border: "#e3e9f1",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #f6f8fb, #eaf0f7)",
    heroText: "#0f172a",
    heroMuted: "#526077",
    onAccent: "#ffffff",
    headingFont: "'Inter Tight', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    googleFonts: gf("family=Inter+Tight:wght@500;700&family=Inter:wght@400;500;600"),
    radius: 10,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "border",
    serviceStyle: "grid",
    divider: "none",
  },
  {
    id: "espresso",
    label: "Espresso — kahvilan lämpö",
    categories: ["hospitality"],
    vibes: ["warm", "elegant"],
    accent: "#7c4a2d",
    accent2: "#a06b48",
    ink: "#2b2018",
    muted: "#6e5c4e",
    bg: "#fbf7f2",
    surface: "#f3ebe2",
    card: "#ffffff",
    border: "#e6d9cb",
    inputBg: "#ffffff",
    heroBg: "linear-gradient(135deg, #f3ebe2, #e9dccd)",
    heroText: "#2b2018",
    heroMuted: "#6e5c4e",
    onAccent: "#ffffff",
    headingFont: "'Bitter', Georgia, serif",
    bodyFont: "'Karla', system-ui, sans-serif",
    googleFonts: gf("family=Bitter:wght@500;700&family=Karla:wght@400;600;700"),
    radius: 10,
    borderW: 1,
    heroStyle: "left",
    cardStyle: "filled",
    serviceStyle: "grid",
    divider: "wave",
  },
];

function hashStr(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

const CATEGORIES: TemplateId[] = ["salon", "trades", "hospitality"];

/**
 * Resolve the theme for a site. Priority: explicit editor pick (themeId) → category
 * pool narrowed by the AI's vibe when it matches → deterministic index from
 * designSeed / business-name hash. Same input → same theme.
 */
export function pickTheme(content: SiteContent, templateId: string): Theme {
  if (content.themeId) {
    const chosen = THEMES.find((t) => t.id === content.themeId);
    if (chosen) return chosen;
  }

  const category = (CATEGORIES.includes(templateId as TemplateId)
    ? templateId
    : "trades") as TemplateId;
  let pool = THEMES.filter((t) => t.categories.includes(category));
  if (!pool.length) pool = THEMES;

  if (content.vibe) {
    const vibed = pool.filter((t) => t.vibes.includes(content.vibe as Vibe));
    if (vibed.length) pool = vibed;
  }

  const seed =
    content.designSeed ??
    hashStr(content.businessName || content.source?.name || "site");
  return pool[seed % pool.length];
}
